[pytest]
;testpaths =
;    tests
;    sprinkles

;pythonpath =
;    src
;    examples
;    tests
;    ../coppertop/src
;    ../coppertop/bk/lib
;    ../bones/src

addopts =
    --import-mode importlib
    --strict-markers
;    -m "not slow"     ; uncomment to skip slow tests
;    --ignore=tests/bones/lang/test_partitions.py
;    --ignore=tests/bones/lang/test_snippets.py
;
; performance benchmarks:
;   tests under profiling/tight_loop_performance and profiling/exception_performance are skipped by default.
;   to run them, add either of:
;     - command line:  pytest --tight_loop_performance
;     - here (not recommended globally):  --tight_loop_performance

markers =
    bones_lang
    type_lang
    type_system
    needs_work
    slow
    tight_loop_performance
    performance_test

python_files =
    test_*.py
    ex_*.py

console_output_style = progress



;src:tests:../coppertop/src:../coppertop/bk/lib:../bones/src